FactoryData/Controllers/FAMController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FactoryData.Models;
using PagedList;
using PagedList.Mvc;
using System.Data.SqlClient;
using System.Data;
using System.IO;
using NPOI.SS.UserModel;
using NPOI.XSSF.UserModel;
using NPOI.HSSF.UserModel;

namespace FactoryData.Controllers
{
    public class FAMController : Controller
    {
        //string sql = @"server=COSDF15P6VSS21\SQLEXPRESS;initial catalog=FactoryData;user id=sa;password=iamthegad123";//實體server
        //string sql = @"server=COSDF15P6VSS21\SQLEXPRESS;initial catalog=FactoryData;user id=sa;password=iamthegad123";//寫程式的Server
        //string sql = @"server=192.168.1.36;initial catalog=FactoryData;user id=sa;password=iamthegad123";//公司筆電
        string sql = @"server=192.168.1.36;initial catalog=FactoryData;user id=sa;password=iamthegad123";//公司筆電
        // GET: FAM
        SqlConnection sc = new SqlConnection();
        public ActionResult Index()
        {
            return View();
        }
        public void CommandQuerytosql(string sqlcom) //SQL指令回傳至資料庫
        {
            sc.ConnectionString = sql;
            sc.Open();
            SqlCommand com = new SqlCommand(sqlcom, sc);
            com.ExecuteNonQuery();//SqlCommand導入資料庫
            sc.Close();
        }
        public DataTable da(string sqlcom)//顯示資料庫資料
        {
            sc.ConnectionString = sql;
            SqlDataAdapter sd = new SqlDataAdapter(sqlcom, sc);
            DataSet ds = new DataSet();
            sd.Fill(ds);
            return ds.Tables[0];
        }
        public ActionResult SMSCCTV(int ? page,int ? PageSize,string searchCCTVNumber)
        {
            List<SMSCCTVModel> list = new List<SMSCCTVModel>();//SMSCCTVModel的泛型空間
            string strCCTV = "";
            ViewBag.PageSize = new List<SelectListItem>()//數值放入ViewBag暫存
            {
                new SelectListItem() { Value="10", Text= "10" },
                new SelectListItem() { Value="30", Text= "30" },
                new SelectListItem() { Value="50", Text= "50" },
                new SelectListItem() { Value="100", Text= "100" },
                new SelectListItem() { Value="200", Text= "200" },
            };
            int pageNumber = (page ?? 1);
            int pagesize = (PageSize ?? 10);
            ViewBag.psize = pagesize;
            if (!string.IsNullOrEmpty(searchCCTVNumber))
            {
                strCCTV = "Select *from SMSCCTV WHERE ProductNumber like '%" + searchCCTVNumber + "%'";
            }
            else
            {
                strCCTV = "select *from SMSCCTV order by ID DESC";
            }
            ReturnPermit ret = new ReturnPermit();
            String SMSCCTV1 = ret.returnSMSCCTV(Session["Permit"].ToString(), sql);//取得驗證權限的資訊
            if (SMSCCTV1 == "授權")
            {


                DataTable dt = da(strCCTV);
                for (int i = 0; i < dt.Rows.Count; i++)
                {
                    SMSCCTVModel ins = new SMSCCTVModel();
                    ins.ID = dt.Rows[i]["ID"].ToString();
                    ins.RemoveClass = dt.Rows[i]["RemoveClass"].ToString();
                    ins.System = dt.Rows[i]["System"].ToString();
                    ins.SonSystem = dt.Rows[i]["SonSystem"].ToString();
                    ins.ProductNumber = dt.Rows[i]["ProductNumber"].ToString();
                    ins.ProductDescription = dt.Rows[i]["ProductDescription"].ToString();
                    ins.Factory = dt.Rows[i]["Factory"].ToString();
                    ins.Phase = dt.Rows[i]["Phase"].ToString();
                    ins.Buliding = dt.Rows[i]["Buliding"].ToString();
                    ins.Floor = dt.Rows[i]["Floor"].ToString();
                    ins.ClassNO = dt.Rows[i]["ClassNO"].ToString();
                    ins.DeviceClass = dt.Rows[i]["DeviceClass"].ToString();
                    ins.Brand = dt.Rows[i]["Brand"].ToString();
                    ins.Type = dt.Rows[i]["Type"].ToString();
                    ins.ProductClassful = dt.Rows[i]["ProductClassful"].ToString();
                    ins.RackPeople = dt.Rows[i]["RackPeople"].ToString();
                    ins.Remarks = dt.Rows[i]["Remarks"].ToString();
                    ins.AddDatetime = dt.Rows[i]["AddDatetime"].ToString();
                    ins.Machinestate = dt.Rows[i]["Machinestate"].ToString();
                    ins.DownDate = dt.Rows[i]["DownDate"].ToString();
                    ins.EditDatetime = dt.Rows[i]["EditDatetime"].ToString();                  
                    list.Add(ins);
                }
                var pagelist = list.ToPagedList(pageNumber, pagesize);
                return View(pagelist);
            }
            else
            {
                return RedirectToAction("NoAuthorityView","Home");
            }

        }
        [HttpPost]
        public ActionResult InsertSMSCCTV(SMSCCTVModel insc)//新增SMSCCTV的資訊
        {
            sc.ConnectionString = sql;
            string insertStr = "insert into SMSCCTV(RemoveClass,System,SonSystem,ProductNumber,ProductDescription,Factory,Phase,Buliding,Floor,ClassNO,DeviceClass,Brand,Type,ProductClassful,RackPeople,Remarks,AddDatetime,Machinestate,DownDate)" +
                "VALUES('" + insc.RemoveClass + "','" + insc.System + "','" + insc.SonSystem + "','" + insc.ProductNumber + "','" + insc.ProductDescription + "','" + insc.Factory + "','" + insc.Phase + "','"
                + insc.Buliding + "','" + insc.Floor + "','" + insc.ClassNO + "','" + insc.DeviceClass + "','" +insc.Brand + "','" +insc.Type + "','"+insc.ProductClassful + "','"+insc.RackPeople + "','"+insc.Remarks + "','" +insc.AddDatetime + "','" +insc.Machinestate + "','" + insc.DownDate + "')";
            //string.Format("insert into DeviceSwitchPort(ID,SwitchName,SwitchPort,DeviceType,AddDatetime,EditDatetime" +
            //")VALUES(" + ins.ID + "," + ins.SwitchName.Replace("'","''") + "," + ins.SwitchPort.Replace("'","''") + "," + ins.DeviceType.Replace("'","''")
            //+ "," + ins.AddDatetime.Replace("'","''") + "," + ins.EditDatetime.Replace("'","''") + ")"
            //);
            CommandQuerytosql(insertStr);
            return RedirectToAction("SMSCCTV");

        }
        public ActionResult InsertSMSCCTV(FabModel fab)
        {
            string selectFab = string.Format("Select* from Fab");
            DataTable dt = da(selectFab);
            return View(dt);
        }
        public ActionResult SMSCCTVUpload()
        {
            return View();
        }
        [HttpPost]
        public ActionResult SMSCCTVUpload(SMSCCTVModel dev, HttpPostedFileBase file)
        {
            string extension =
                    System.IO.Path.GetExtension(file.FileName);

            if (extension == ".xls" || extension == ".xlsx")
            {
                string fileLocation = Server.MapPath("~/Upload/") + file.FileName;
                file.SaveAs(fileLocation); // 存放檔案到伺服器上               
            }
            //String filePath = @"D:\20201205廠區寫的Web\FactoryData - 複製\FactoryData\Upload\" + file.FileName;//測試用
            String filePath = @"C:\20201218廠區資料\20201218場內寫的WEB\20201205廠區寫的Web\FactoryData - 複製\FactoryData\Upload\" + file.FileName;//測試用

            //String filePath = @"D:\NewWeb\Upload\" + file.FileName;

            IWorkbook workbook = null;
            FileStream fs = new FileStream(filePath, FileMode.Open, FileAccess.Read);
            if (filePath.IndexOf(".xlsx") > 0)
                workbook = new XSSFWorkbook(fs);
            else if (filePath.IndexOf(".xls") > 0)
                workbook = new HSSFWorkbook(fs);
            ISheet sheet = workbook.GetSheetAt(0);
            if (sheet != null)
            {
                int rowCount = sheet.LastRowNum;
                for (int i = 1; i <= rowCount; i++)
                {
                    IRow curROw = sheet.GetRow(i);
                    dev.RemoveClass = curROw.GetCell(0).ToString();
                    dev.System = curROw.GetCell(1).ToString();
                    dev.SonSystem = curROw.GetCell(2).ToString();
                    dev.ProductNumber = curROw.GetCell(3).ToString();
                    dev.ProductDescription = curROw.GetCell(4).ToString();
                    dev.Factory = curROw.GetCell(5).ToString();
                    dev.Phase = curROw.GetCell(6).ToString();
                    dev.Buliding = curROw.GetCell(7).ToString();
                    dev.Floor = curROw.GetCell(8).ToString();
                    dev.ClassNO = curROw.GetCell(9).ToString();
                    dev.DeviceClass = curROw.GetCell(10).ToString();
                    dev.Brand = curROw.GetCell(11).ToString();
                    dev.Type = curROw.GetCell(12).ToString();
                    dev.ProductClassful = curROw.GetCell(13).ToString();
                    dev.RackPeople = curROw.GetCell(14).ToString();
                    dev.Remarks = curROw.GetCell(15).ToString();
                    dev.AddDatetime = curROw.GetCell(16).ToString();
                    dev.Machinestate = curROw.GetCell(17).ToString();
                    dev.DownDate= curROw.GetCell(18).ToString();
                    string insertStr = "insert into SMSCCTV(RemoveClass,System,SonSystem,ProductNumber,ProductDescription,Factory,Phase,Buliding,Floor,ClassNO,DeviceClass,Brand,Type,ProductClassful,RackPeople,Remarks,AddDatetime,Machinestate,DownDate)" +
                "VALUES('" + dev.RemoveClass + "','" + dev.System + "','" + dev.SonSystem + "','" + dev.ProductNumber + "','" + dev.ProductDescription + "','" + dev.Factory + "','" + dev.Phase + "','"
                + dev.Buliding + "','" + dev.Floor + "','" + dev.ClassNO + "','" + dev.DeviceClass + "','" + dev.Brand + "','" + dev.Type + "','" + dev.ProductClassful + "','" + dev.RackPeople + "','" + dev.Remarks + "','" + dev.AddDatetime + "','"+dev.Machinestate+"','" +dev.DownDate + "')";
                    CommandQuerytosql(insertStr);

FactoryData/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using FactoryData.Models;
using System.Globalization;
using System.Data.SqlClient;
using System.Security.Cryptography;
using System.Text;
namespace FactoryData.Controllers
{
    public class LoginController : Controller
    {
        public ActionResult Login() 
        {
            return View(); ;
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Logout() {
            FormsAuthentication.SignOut();
            Session.Abandon();
            // clear authentication cookie
            //HttpCookie cookie1 = new HttpCookie(FormsAuthentication.FormsCookieName, "");
            //cookie1.Expires = DateTime.Now.AddYears(-1);
            //Response.Cookies.Add(cookie1);           
            //FormsAuthentication.RedirectToLoginPage(); 
            return RedirectToAction("Index", "Home", null);
        }
        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Login(Login login)
        {
            FactoryDataEntities2 db= new FactoryDataEntities2();// 登入的密碼（以 SHA1 加密）   

            //這一條是去資料庫抓取輸入的帳號密碼的方法請自行實做
            //login.UserPassWord = FormsAuthentication.HashPasswordForStoringInConfigFile(login.UserPassWord, "SHA1");
            //SHA1CryptoServiceProvider sha1 = new SHA1CryptoServiceProvider();
            
            //byte[] password_bytes = Encoding.ASCII.GetBytes(login.UserPassWord);
            //byte[] encrypt_bytes = sha1.ComputeHash(password_bytes);
            //string loginpass = Convert.ToString(encrypt_bytes);            
            var r = db.Account.Where(x => x.UserName == login.UserName && x.UserPassWord == login.UserPassWord).FirstOrDefault();
            
                if (r == null)
                {
                    TempData["Error"] = "您輸入的帳號不存在或者密碼錯誤!";
                    return View();
                }
                else if (r != null)
                {
                    Session["UserID"] = r.ID.ToString();
                    Session["Remarks"] = r.Remarks.ToString();
                    Session["UserName"] = r.UserName.ToString();
                    Session["Permit"] = r.Permit.ToString();
                    
                }
           
            // 登入時清空所有 Session 資料
            //Session.RemoveAll();
            FormsAuthenticationTicket ticket = new FormsAuthenticationTicket(
              r.ID,
              r.UserName,//你想要存放在 User.Identy.Name 的值，通常是使用者帳號
              DateTime.Now,
              DateTime.Now.AddMinutes(30),
              false,//將管理者登入的 Cookie 設定成 Session Cookie
              r.Remarks.ToString(),//userdata看你想存放甚麼資訊
              FormsAuthentication.FormsCookiePath);
            string encTicket = FormsAuthentication.Encrypt(ticket);
            Response.Cookies.Add(new HttpCookie(FormsAuthentication.FormsCookieName,encTicket));
            return RedirectToAction("Index", "Home");
        }
        // GET: Account

        //public ActionResult Login(Login model)
        //{
        //FactoryDataEntities db = new FactoryDataEntities();
        //if (!ModelState.IsValid)
        //{
        //    return View(model);
        //}

        //var user = db.Account.Where(x => x.UserName == model.UserName && x.UserPassWord == model.UserPassWord).FirstOrDefault();

        //if (user == null)
        //{
        //    ModelState.AddModelError("", "無效的帳號或密碼。");
        //    return View();
        //}

        //var ticket = new FormsAuthenticationTicket(
        //            version: 1,
        //            name: user.ID.ToString(), //可以放使用者Id
        //            issueDate: DateTime.UtcNow,//現在UTC時間
        //            expiration: DateTime.UtcNow.AddMinutes(30),//Cookie有效時間=現在時間往後+30分鐘
        //            isPersistent: true,// 是否要記住我 true or false
        //            userData, //可以放使用者角色名稱
        //            cookiePath: FormsAuthentication.FormsCookiePath);

        //var encryptedTicket = FormsAuthentication.Encrypt(ticket); //把驗證的表單加密
        //var cookie = new HttpCookie(FormsAuthentication.FormsCookieName, encryptedTicket);
        //Response.Cookies.Add(cookie);
        //    return RedirectToAction("Index", "Home");
        //}
    }
}

FactoryData/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>歡迎來到F15B廠區資料系統</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" type="text/css" href="~/Content/navbarmenu.css">
</head>
<body>
        <div class="navbar navbar-inverse navbar-fixed-top navbar-">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("首頁", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>

                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li class="dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="FactoryInsideInformation" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                廠內設備資訊
                            </a>
                            <ul class="dropdown-menu navmenuleft" aria-labelledby="FactoryInsideInformation" style="background-color:powderblue">
                                <li>@Html.ActionLink("門禁新增資訊", "Door", "Home")</li>
                                <li>@Html.ActionLink("CCTV新增資訊", "CCTV", "Home")</li>
                                <li>@Html.ActionLink("F15B廠區設備裝置SWITCH阜位", "DeviceSwitchPortDisplay", "Home")</li>
                                <li>@Html.ActionLink("新增廠區", "Fab", "Home")</li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="FactoryReportInformation" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                回報資訊
                            </a>
                            <ul class="dropdown-menu navmenuleft" aria-labelledby="FactoryReportInformation" style="background-color:powderblue">
                                <li>@Html.ActionLink("記錄", "ReportDetial", "Home")</li>
                                <li>@Html.ActionLink("業主回報", "OrnerReport", "Home")</li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="FactoryReportInformation" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                FAM資產表
                            </a>
                            <ul class="dropdown-menu navmenuleft" aria-labelledby="FactoryReportInformation" style="background-color:powderblue">
                                <li>@Html.ActionLink("SMSCCTV", "SMSCCTV", "FAM")</li>
                                <li>@Html.ActionLink("SMS-讀卡機", "SMSReader", "FAM")</li>
                                <li>@Html.ActionLink("SMS-AlarmSystem", "SMSAlarmSystem", "FAM")</li>
                                <li>@Html.ActionLink("SMS-柵欄機", "SMSBarriergate", "FAM")</li>
                                <li>@Html.ActionLink("SMS-通關機", "SMSGate", "FAM")</li>
                                <li>@Html.ActionLink("SMS-製證機", "SMSMakeCard", "FAM")</li>

                            </ul>
                        </li>
                        <li class="dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="FactoryAuthorityInformation" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                帳戶管理
                            </a>
                            <ul class="dropdown-menu navmenuleft" aria-labelledby="FactoryAuthorityInformation" style="background-color:powderblue">
                                <li>@Html.ActionLink("新增帳號", "AccountDetail", "Home")</li>
                                <li>@Html.ActionLink("權限設定", "permition", "Home")</li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                使用者
                            </a>
                            <ul class="dropdown-menu navmenucentor" aria-labelledby="navbarDropdownMenuLink" style="background-color:powderblue">
                                @if (Session["Remarks"] != null)
                                {
                                    <li>
                                        <a class="dropdown-item">
                                            Welcome @Session["Remarks"].ToString()
                                        </a>
                                    </li>
                                }
                                <li></li>
                                <li>
                                    <form method="post" action="@Url.Action("Logout", "Login")" enctype="multipart/form-data">
                                        <a href="/Home/EditPassword/" class="btn btn-primary">修改密碼</a>
                                        <button type="submit" class="btn btn-danger">登出</button>
                                        @Html.AntiForgeryToken()
                                    </form>
                                </li>
                            </ul>
                    </ul>
                    @*<li>@Html.ActionLink("權限設定", "AuthorityGroup", "AuthorityDisplay")</li>*@
                </div>               
            </div>
        </div>
        <div class="container body-content">
            @RenderBody()
            <footer>
                <p align="center">&copy; @DateTime.Now.Year - 歡迎使用F15B廠區資料系統</p>
            </footer>
        </div>
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
    </body>

</html>